main: lucatruglia.piratecore.PirateCore
version: 1.0.0
name: PirateCore
author: lucatruglia
api-version: 1.21
softdepend: [PlaceholderAPI, Jobs, rlTrails]
depend: [Vault, ItemEdit, WorldGuard]


commands:
  klevel:
    description: "level command"
    usage: "/klevel"
  kbar:
    description: "level command"
    usage: "/kbar"
  kbarrel:
    description: "level command"
    usage: "/kbarrel"
  kmap:
    description: "level command"
    usage: "/kmap"
  kboat:
    description: "level command"
    usage: "/kboat"
  ktrail:
    description: "level command"
    usage: "/kboat"