main: it.lucatruglia.piratecore.piratecore
version: 1.0.0-SNAPSHOT
name: piratecore
author: lucatruglia
description: A Minecraft development project.
api-version: 1.21

commands:
  ktest:
    description: Manage player bossbars.
    usage: /ktest show | hide [player]
    permission: piratecore.bossbar.use
  klevel:
    description: Manage player levels and XP.
    usage: /klevel info [player] | add <player> <amount> | set <player> <amount>
    permission: piratecore.level.use

permissions:
  piratecore.bossbar.use:
    default: true
  piratecore.bossbar.other:
    default: op
  piratecore.level.use:
    default: true
  piratecore.level.admin:
    default: op
  piratecore.level.other:
    default: op


soft-depend: [PlaceholderAPI]
